language: java
jdk: openjdk8
sudo: required
services:
  - docker
script:
  - docker build -t payroll-api-tests .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag payroll-api-tests $DOCKER_USER/payroll-api-tests:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/payroll-api-tests:$TRAVIS_BUILD_NUMBER
  - docker tag payroll-api-tests $DOCKER_USER/payroll-api-tests:latest
  - docker push $DOCKER_USER/payroll-api-tests:latest